name: epicture
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  bloc: ^7.1.0
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_lints: ^1.0.4
  flutter_localizations:
    sdk: flutter
  flutter_webview_plugin: ^0.4.0
  http: ^0.13.3
  image_picker: ^0.8.4+1
  intl: ^0.17.0
  logger: ^1.0.0

dev_dependencies:
  bloc_test: ^8.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
    version: ^0.0.0
  mocktail: ^0.1.0
  network_image_mock: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  # assets:
  # fonts:
